"""empty message

Revision ID: 23247acf74b4
Revises: ee1ca2d857d8
Create Date: 2020-07-16 14:14:29.086799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23247acf74b4'
down_revision = 'ee1ca2d857d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_file', sa.Column('name', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_file', 'name')
    # ### end Alembic commands ###
