"""empty message

Revision ID: ee1ca2d857d8
Revises: 
Create Date: 2020-07-16 11:56:55.541463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1ca2d857d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('life_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_file')
    # ### end Alembic commands ###
